# -*- coding: utf-8 -*-
"""Generate_multiplication_table_from_1_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRWPfm_uXMdUWz60zf96QLM1FwN6Cc7x
"""

# Generate a multiplication table from 1 to 10.
print("Multiplication Table :\n====================\n")

def print_table() :
  for i in range(1,11) :
    print(f"Table of {i} :")
    for j in range (1,11) :
      table = i*j
      print(f"{i}*{j} = {table}")
    print("\n===============\n")

print_table()